### PR TITLE
Updated for 3.2.x compatibility

### PR DESCRIPTION
**Pull request by CrazyC0d3r**
Hi,

I have updated this extension so that it works with phpBB 3.2.x.

### CODE REVIEW

**Comment by CrazyC0d3r** [comment]
Ah, what's up with the travis? I reverted the changes, will leave that one to you!

**Comment by rmcgirr83** [comment]
See https://github.com/rmcgirr83/phpBB-3.1-activity24hours/blob/master/.travis.yml for inspiration.

**Comment by rmcgirr83** [comment]
Boom!! 👍

**Comment by Leinad4Mind** [comment]
Thanks for this @CrazyC0d3r

**Comment by CrazyC0d3r** [comment]
Currently this extension achieves it's goal at marking edited posts by updating the post time in the database. Unfortunately, by doing so it also changes the post date and time to the current date and time at the time of submitting the edited post.

What it should be doing is modifying the "mark_time" to "zero" in the "phpbb_forums_track" table. By changing the "mark_time" to "zero" the topic is marked as unread again without changing the original post date and time.

Currently in testing and seems to work well. Can you tell me any reason why it shouldn't be done this way?

**Comment by Leinad4Mind** [comment]
What about:

SET topic_last_post_time = ' . time() . '
and 
SET post_time = ' . time() . '

be something like:
SET topic_last_post_time = topic_last_post_time + 1 (+ or - dunno what the best)
and 
SET post_time = post_time +1

This way the time would be different and maybe would be enough for this to work.

Read this: https://github.com/kasimi/phpbb-ext-markpostunread/blob/master/kasimi/markpostunread/includes/core.php#L143-L155

I dont have time right now to dig deeper.

**Comment by CrazyC0d3r** [comment]
No that didn't work either.

For now, I have edited the code so that the first posts date and time isn't updated in order to prevent messing up topics.

```
	public function submit_post_end($event)
	{
		if ($event['mode'] == 'edit')
		{
			$ext_post_mode = '';
			if ($event['data']['topic_posts_approved'] + $event['data']['topic_posts_unapproved'] + $event['data']['topic_posts_softdeleted'] == 1)
			{
				$ext_post_mode = 'edit_topic';
			}
			else if ($event['data']['topic_first_post_id'] == $event['data']['post_id'])
			{
				$ext_post_mode = 'edit_first_post';
			}
			else if ($event['data']['topic_last_post_id'] == $event['data']['post_id'])
			{
				$ext_post_mode = 'edit_last_post';
			}

			if ($ext_post_mode == 'edit_last_post' || $ext_post_mode == 'edit_topic')
			{
				$sql = 'UPDATE ' . POSTS_TABLE . '
					SET post_time = ' . time() . '
					WHERE post_id = ' . $event['data']['post_id'] . '
						AND topic_id = ' . $event['data']['topic_id'];
				$this->db->sql_query($sql);

				$sql = 'UPDATE ' . TOPICS_TABLE . '
					SET topic_last_post_time = ' . time() . '
					WHERE topic_id = ' . $event['data']['topic_id'];
				$this->db->sql_query($sql);

				if (!function_exists('update_post_information'))
				{
					include ($this->root_path . 'includes/functions_posting.' . $this->php_ext);
				}

				update_post_information('forum', $event['data']['forum_id']);
				markread('post', $event['data']['forum_id'], $event['data']['topic_id'], $event['data']['post_time']);
			}
		}
	}
```

I will look into this some more and read the topics you linked to.

**Comment by Leinad4Mind** [comment]
Any news at this?

**Pull request merged**
